### 1. Một số lưu ý về lập trình Python với đại số tuyến tính

##### 1.3.   Các phép xử lí với danh sách 

In [91]:
# Khởi tạo danh sách
danhsach1 = [1,2,3]
danhsach2 = [5,6,7]

In [92]:
# Nối 2 danh sách bằng toán tử +
danhsach = danhsach1 + danhsach2
danhsach

[1, 2, 3, 5, 6, 7]

In [93]:
# Gấp đôi danh sách
danhsach_gapdoi = 2*danhsach
danhsach_gapdoi

[1, 2, 3, 5, 6, 7, 1, 2, 3, 5, 6, 7]

In [94]:
danhsach*2

[1, 2, 3, 5, 6, 7, 1, 2, 3, 5, 6, 7]

In [95]:
# danhsach / 2 # Chương trình sẽ thông báo lỗi vì không thể chia list cho một số nguyên

In [96]:
# Ghép các danh sách bằng lệnh zip
mon_hoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"]
thu_tu = [2, 3, 4, 1]
diem_so = [10, 9, 8, 7]
anh_xa = zip(thu_tu, mon_hoc, diem_so)
anh_xa ## anh_xa la mot doi tuong zip


In [97]:
tap_hop = set(anh_xa) # Chuyển zip thành dạng tập hợp
tap_hop

{(1, 'LaptrinhCB', 7), (2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8)}

In [98]:
# Phân rã đối tượng zip
lay_TT , lay_monhoc , lay_diem = zip(*anh_xa)
lay_monhoc

ValueError: not enough values to unpack (expected 3, got 0)

* Xây dựng danh sách: Bên cạnh những cách khai báo danh sách thông thường như: khai báo
sẵn hoặc khai báo list rỗng rồi bổ sung phần tử bằng lệnh append, cơ chế sinh tập hợp list
trong Python còn có thể thực hiện bằng các cách sau:

In [ ]:
import itertools
tap_sinh = list(itertools.chain(range(4), range(5,10), range(15,20)))
tap_sinh

[0, 1, 2, 3, 5, 6, 7, 8, 9, 15, 16, 17, 18, 19]

In [ ]:
# Tạo ra tập sinh nhiều chiều
list(zip(range(4), range(7, 12), reversed(range(11) ) ) )

[(0, 7, 10), (1, 8, 9), (2, 9, 8), (3, 10, 7)]

##### 1.4. Lệnh thực thi một tập tin python

In [176]:
# execfile('test.py')

### 2. Các gói thư viện cơ bản tích hợp trong Python hỗ trợ toán học

Hàm $expm1(x)$ trong thư viện math trả về giá trị $e^x - 1$ \
Hàm $exp(x)$ trong thư viện math trả về giá trị $e^x$

In [ ]:
import math
x = 1
print(math.expm1(x) == math.exp(x)-1) # True

True


In [ ]:
x = 1e-5
print(math.expm1(x) == math.exp(x)-1) # False
print(math.exp(x)-1)
print(math.expm1(x))
# Bởi  vì 1e-5 là số thực rất nhỏ nên e^x  sẽ có sai số nên dẫn đến kết quả False

False
1.0000050000069649e-05
1.0000050000166668e-05


### 3. Làm quen với thư viện NumPy

#### 3.1. Một số lệnh cơ bản numpy xử lí vector

In [102]:
# Khởi tạo vector
import numpy as np
vec1 = np.array([1, 2, 3,4, 5])

In [103]:
# Nhân vector với một số  thực
vec1 * 2

array([ 2,  4,  6,  8, 10])

In [104]:
vec1/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [107]:
# Nhân 2 vector với nhau 
vec1*vec1

array([ 1,  4,  9, 16, 25])

In [108]:
# Cộng 2 vector
vec1 + vec1

array([ 2,  4,  6,  8, 10])

In [111]:
vec2 = np.array([2,3,4])
vec1 + vec2 # Chương trình sẽ thông báo lỗi vì vec1 và vec2  không cùng kích thước nên không thể cộng được

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [113]:
vec3 = np.array([2,3,4,5,6])
vec1 + vec3

array([ 3,  5,  7,  9, 11])

In [115]:
# chia 2 vector -> Từng phần tử của vector bị chia chia cho từng phần tử của vector chia
vec1/vec3

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333])

In [116]:
vec1 * vec3

array([ 2,  6, 12, 20, 30])

In [118]:
2* vec1 + 5* vec3

array([12, 19, 26, 33, 40])

Truy xuất đến phần tử của vector:

In [119]:
vec3[2]

4

Tạo vector thông qua câu lệnh linspace(phần tử đầu, phần tử cuối, số lượng phần tử)

In [121]:
vec4 = np.linspace(0, 20, 5)
vec4

array([ 0.,  5., 10., 15., 20.])

Tạo các vector toàn 0

In [122]:
vec5 = np.zeros(5)
vec5

array([0., 0., 0., 0., 0.])

Tạo các vector toàn 1

In [123]:
vec6 = np.ones(5)
vec6

array([1., 1., 1., 1., 1.])

Tạo vector ảo (giá trị rỗng)

In [124]:
vec7 = np.empty(5)
vec7

array([1., 1., 1., 1., 1.])

Tạo vector các giá trị ngẫu nhiên từ 0 đến 1

In [125]:
np.random.random(5)

array([0.46659293, 0.75556232, 0.40349714, 0.63620044, 0.60051926])

In [126]:
v = np.array([1,2,3,4,5])

Lệnh lấy tổng các thành phần của vector

In [127]:
np.sum(v)

15

Lệnh xem số chiều của một vector

In [128]:
v.shape

(5,)

Thử nghiệm “chuyển vị” vector

In [129]:
v.transpose()

array([1, 2, 3, 4, 5])

Lệnh lấy một phần của vector

In [131]:
v1 = v[:2]
v1

array([1, 2])

In [132]:
v[0] = 5
v

array([5, 2, 3, 4, 5])

In [133]:
v1

array([5, 2])

In [136]:
v1[:2] = [1, 2, 3] # Chương trình thông báo lỗi vì không cùng kích thước

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [137]:
v1[:2] = [1, 2]
v1

array([1, 2])

In [138]:
v3 = 2 * v[:2] + v1 * 3
v3

array([ 5, 10])

In [139]:
v1 = [4, 6]
v3

array([ 5, 10])

In [140]:
v

array([1, 2, 3, 4, 5])

Các phép toán trên vector: trên vector, chúng ta có thể thực hiện phép toán như: lấy 
sin/cos

In [141]:
v + 10.0

array([11., 12., 13., 14., 15.])

In [142]:
np.sqrt(v)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [143]:
np.cos(v)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [145]:
np.sin(v)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

 Tích vô hướng của hai vector (kết quả là một số)

In [146]:
np.dot(v1, v3)

80

In [148]:
v1.dot(v3) # Lỗi
v3.dot(v1) # Lỗi

AttributeError: 'list' object has no attribute 'dot'

Độ dài (chuẩn 2) và chuẩn 1 của vector (độ dài theo Euclide): \
$\vec{v_1} = (a,b)$ : $|\vec{v_1}| = \sqrt{a^2 + b^2}$ ; $||\vec{v_1}|| = |a| + |b|$ 

In [149]:
np.linalg.norm(v)

7.416198487095663

Độ dài (kích thước) của vector

In [151]:
len(v)

5

Kết nối các vector

In [152]:
np.hstack([v, v3])

array([ 1,  2,  3,  4,  5,  5, 10])

Bài tập thực hành

In [153]:
def symp(v):
    n = len(v) // 2
    return np.hstack([-v[-n:], v[:n]])
v6 = np.array([1., 3., 5., 7., 9., 11.])
v7 = symp(v6)
v7


array([ -7.,  -9., -11.,   1.,   3.,   5.])

#### 3.2. Thể hiện ma trận bằng numpy

Ma trận được thể hiện trong numpy là nhiều dãy [] trong kiểu khai báo array. \
Ví dụ : ma trận $M_1$ = $\left[\begin{matrix} 9 & 12 \\ 23 & 30 \end{matrix}\right]$ được khai báo như sau :

In [154]:
M1 = np.array([ [9, 12], [23,30] ])
M1

array([[ 9, 12],
       [23, 30]])

Khi đó, giả sử chúng ta có một vector $u = (2,1)$ thì $tích$ giữa hai ma trận và vector $M_1u$ sẽ là :

In [155]:
u = np.array([2,1])
tichM1u = M1.dot(u)
tichM1u

array([30, 76])

In [156]:
tichuM1 = u.dot(M1)
tichuM1

array([41, 54])

In [158]:
np.dot(M1, u)

array([30, 76])

In [159]:
np.dot(u, M1)

array([41, 54])

##### Bài tập trên lớp

1. \
Lệnh mat1 = $np.zeros([5,5])$ sẽ tạo một ma trận 0 với kích thước $5*5$ \
Cụ thể , mat1 = $\left[\begin{matrix} 0 & 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 & 0 \end{matrix} \right] $

In [29]:
import numpy as np 
mat1 = np.zeros([5,5])
mat1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

2. \
Lệnh mat2 = $np.ones([5,5])$ sẽ tạo ra một ma trận có kích thước $5*5$ và có các phần tử bằng $1$  \
Cụ thể , mat2 = $\left[\begin{matrix} 1 & 1 & 1 & 1 & 1 \\ 1 & 1 & 1 & 1 & 1 \\ 1 & 1 & 1 & 1 & 1 \\ 1 & 1 & 1 & 1 & 1 \\ 1 & 1 & 1 & 1 & 1 \end{matrix} \right] $

In [30]:
mat2 = np.ones([5,5])
mat2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

3. \
Lệnh mat3 = mat1 + 2 * mat2 sẽ tạo ra một ma trận $mat3$ với các phần tử bằng với các phần tử tương ứng của $mat1$ + 2 * các phần tử tương của $mat2$, cụ thể như sau : \
mat3 = $\left[\begin{matrix} 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 \\ 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 \\ 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 \\ 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 \\ 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 \end{matrix} \right] = \left[\begin{matrix} 2 & 2 & 2 & 2 & 2 \\ 2 & 2 & 2 & 2 & 2 \\ 2 & 2 & 2 & 2 & 2 \\ 2 & 2 & 2 & 2 & 2 \\ 2 & 2 & 2 & 2 & 2 \end{matrix} \right]  $


In [31]:
mat3 = mat1 + 2*mat2
print(mat3)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


4. \
Lệnh mat4 = mat3 sẽ tạo ra một ma trận có các phần tử bằng với mat3. Khi một phần tử thay đổi trên mat3 thì phần tử tại vị trí tương ứng trong mat4 sẽ thay đổi theo bởi vì mat4 đang lưu địa chỉ của mat3 nên khi mat3 thay đổi thì mat4 sẽ thay đổi

In [32]:
mat4 = mat3
mat3[3][2] = 10
print("mat3", '\n' ,mat3)
print('mat4\n',mat4)

mat3 
 [[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]
mat4
 [[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]


5. \
Lệnh $mat5 = np.copy(mat3)$ sẽ tạo ra một ma trận $mat5$ là bản sao của $mat3$. Khi thay đổi trên $mat3$ sẽ không ảnh hưởng đến $mat5$

In [33]:
mat5 = np.copy(mat3)
mat3[3][2] = 8
print("mat3\n" , mat3)
print("mat4\n", mat4)
print("mat5\n", mat5)

mat3
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 8. 2. 2.]
 [2. 2. 2. 2. 2.]]
mat4
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 8. 2. 2.]
 [2. 2. 2. 2. 2.]]
mat5
 [[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]


6. \
Lệnh $mat6 = np.empty([4,5])$ sẽ tạo ra một ma trận $mat6$ với kích thước là 4*5 và các phần tử trong ma trận là ngẫu nhiên hoặc các giá trị từ bộ nhớ hiện tại

In [34]:
mat6 = np.empty([4,5])
mat6

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.22647253e-307, 1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
        1.37962320e-306, 1.29060871e-306],
       [2.22518251e-306, 1.33511969e-306, 1.78022342e-306,
        1.05700345e-307, 3.11525958e-307],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 1.29062229e-306]])

7. \
Lệnh $mat7 = np.identity(4)$ sẽ tạo một ma trận đơn vị $4*4$ \
Cụ thể , mat7 = $\left[\begin{matrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{matrix} \right] $

In [35]:
mat7 = np.identity(4)
mat7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

8. \
Lệnh $mat8 = np.random.random([4,5])$ sẽ tạo ra một ma trận kích thước $4*5$ và các phần tử trong ma trận là ngẫu nhiên

In [36]:
mat8 = np.random.random([4,5])
mat8

array([[0.64247543, 0.02874175, 0.42861877, 0.96396317, 0.42823961],
       [0.42930769, 0.03177833, 0.08662151, 0.67226185, 0.32887796],
       [0.63588536, 0.63132839, 0.13023494, 0.77879982, 0.88648123],
       [0.54148634, 0.19083888, 0.23320687, 0.71506189, 0.96100693]])

### 5. Tài nguyên Python trên mạng về tính toán đại số

In [171]:
import sympy as sp
M = sp.Matrix([[1, 3], [2, 4]])
M

Matrix([
[1, 3],
[2, 4]])

In [172]:
M.det()

-2

In [175]:
v1 = sp.Matrix([5,7])
M.dot(v1)

ShapeError: 

### Bài tập chương 1

Bài 1

In [37]:
matrix = np.array([[7,8,9,5],[8,7,4,6],[7,5,8,6],[6,8,5,4],[9,9,8,7],[10,8,9,8]])
matrix.shape
percent = [0.1, 0.2, 0.3, 0.4]
AVG = np.dot(matrix,percent)
# print(AVG)
resume = []
passed = []
for i in range (len(AVG)):
    resume.append([chr(ord('A')+i),round(AVG[i],2)])
    if AVG[i] >= 5 :
        passed.append(chr(ord('A')+i))
print("Diem trung binh cua tung hoc sinh")
for student in resume :
    print(student)
print("Danh sach sinh vien qua mon ")
for student in passed :
    print(student) 

Diem trung binh cua tung hoc sinh
['A', 7.0]
['B', 5.8]
['C', 6.5]
['D', 5.3]
['E', 7.9]
['F', 8.5]
Danh sach sinh vien qua mon 
A
B
C
D
E
F


Bài 2 

In [38]:
# Sinh ngẫu nhiên ma trận 3*3 và có các phần tử nguyên từ 0 đến 10
matrix_random1 = np.random.randint(0,10,size=(3,3))
matrix_random2 = np.random.randint(0,10,size=(3,3))
print("Matrix 1 : \n",matrix_random1)
print("Matrix 2 : \n", matrix_random2)

Matrix 1 : 
 [[5 4 4]
 [6 1 5]
 [0 0 9]]
Matrix 2 : 
 [[5 2 0]
 [0 0 3]
 [3 1 0]]


- a) Tính tổng phần tử của mỗi ma trận 

In [39]:
sum_mat1 = sum(sum(matrix_random1))
sum_mat2 = sum(sum(matrix_random2))
print("Tong phan tu cua ma tran 1 : ", sum_mat1)
print("Tong phan tu cua ma tran 2 : ", sum_mat2)

Tong phan tu cua ma tran 1 :  34
Tong phan tu cua ma tran 2 :  14


- b)  So sánh norm của vector hàng 1 và vector hàng 3 của hai ma trận

In [42]:
mat1_row1 = np.linalg.norm(matrix_random1[0])
mat1_row3 = np.linalg.norm(matrix_random1[2])
mat2_row1 = np.linalg.norm(matrix_random2[0])
mat2_row3 = np.linalg.norm(matrix_random2[2])
print("Mat1_row1 : ",mat1_row1)
print("Mat1_row3 : ",mat1_row3)
print("Mat2_row1 : ",mat2_row1)
print("Mat2_row3 : ",mat2_row3)

# So sanh
if mat1_row1 > mat1_row3 :
    print("Mat1_row1 > Mat1_row3 ")
elif mat1_row1 < mat1_row3 :
    print("Math1_row1 < Mat1_row3")
else:
    print("Math1_row1 = Mat1_row3")

if mat2_row1 > mat2_row3 :
    print("Mat2_row1 > Mat2_row3")
elif mat2_row1 < mat2_row3 :
    print("Mat1_row3 < Mat2_row3")
else:
    print("Mat2_row1 = Mat2_row3")

Mat1_row1 :  7.54983443527075
Mat1_row3 :  9.0
Mat2_row1 :  5.385164807134504
Mat2_row3 :  3.1622776601683795
Math1_row1 < Mat1_row3
Mat2_row1 > Mat2_row3


- c) Tìm ma trận C, D, E là tổng, hiệu, tích của hai ma trận trên.

In [43]:
# Tổng của hai ma trận 
C = matrix_random1 + matrix_random2
# Hiệu của hai ma trận
D = matrix_random1 - matrix_random2
# Tích hai ma trận
E = np.dot(matrix_random1,matrix_random2)
print("C\n", C)
print("D\n",D)
print("E\n",E)

C
 [[10  6  4]
 [ 6  1  8]
 [ 3  1  9]]
D
 [[ 0  2  4]
 [ 6  1  2]
 [-3 -1  9]]
E
 [[37 14 12]
 [45 17  3]
 [27  9  0]]


Bài 3

In [44]:
# Sinh vector
vector1 = np.linspace(0,100,21)
print(vector1)

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]


- a) Dùng lệnh split, chia nhỏ vector kia ra thành 3 vector con, đặt là u, v, w

In [45]:
u,v,w = np.split(vector1,3)
print("u\n", u)
print("v\n",v)
print("w\n",w)

u
 [ 0.  5. 10. 15. 20. 25. 30.]
v
 [35. 40. 45. 50. 55. 60. 65.]
w
 [ 70.  75.  80.  85.  90.  95. 100.]


- b) Tính $u*v$ và $v.dot(w)$

In [46]:
mat_res = u*v
mat_res1 = v.dot(w)
print("u*v\n",mat_res)
print("v.dot(w)\n",mat_res1) 

u*v
 [   0.  200.  450.  750. 1100. 1500. 1950.]
v.dot(w)
 30450.0


- c) Tính shape của u trước và sau khi transpose, nhận xét.

transpose chỉ chuyển vị ma trận , không làm thay đổi kích thước của ma trận nên shape của u trước và sau khi transpose bằng nhau

In [56]:
before_u = u.shape
u.transpose()
after_u = u.shape
print(before_u, after_u)

(7,) (7,)
