### Một số lưu ý về lập trình Python với đại số tuyến tính

##### 1.3.   Các phép xử lí với danh sách 

In [21]:
# Khởi tạo danh sách
danhsach1 = [1,2,3]
danhsach2 = [5,6,7]

In [22]:
# Nối 2 danh sách bằng toán tử +
danhsach = danhsach1 + danhsach2
danhsach

[1, 2, 3, 5, 6, 7]

In [23]:
# Gấp đôi danh sách
danhsach_gapdoi = 2*danhsach
danhsach_gapdoi

[1, 2, 3, 5, 6, 7, 1, 2, 3, 5, 6, 7]

In [24]:
danhsach*2

[1, 2, 3, 5, 6, 7, 1, 2, 3, 5, 6, 7]

In [26]:
danhsach / 2 # Chương trình sẽ thông báo lỗi vì không thể chia list cho một số nguyên

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [38]:
# Ghép các danh sách bằng lệnh zip
mon_hoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"]
thu_tu = [2, 3, 4, 1]
diem_so = [10, 9, 8, 7]
anh_xa = zip(thu_tu, mon_hoc, diem_so)
anh_xa ## anh_xa la mot doi tuong zip


In [34]:
tap_hop = set(anh_xa) # Chuyển zip thành dạng tập hợp
tap_hop

{(1, 'LaptrinhCB', 7), (2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8)}

In [39]:
# Phân rã đối tượng zip
lay_TT , lay_monhoc , lay_diem = zip(*anh_xa)
lay_monhoc

('ToanCC', 'DSTT', 'ToanRR', 'LaptrinhCB')

* Xây dựng danh sách: Bên cạnh những cách khai báo danh sách thông thường như: khai báo
sẵn hoặc khai báo list rỗng rồi bổ sung phần tử bằng lệnh append, cơ chế sinh tập hợp list
trong Python còn có thể thực hiện bằng các cách sau:

In [40]:
import itertools
tap_sinh = list(itertools.chain(range(4), range(5,10), range(15,20)))
tap_sinh

[0, 1, 2, 3, 5, 6, 7, 8, 9, 15, 16, 17, 18, 19]

In [41]:
# Tạo ra tập sinh nhiều chiều
list(zip(range(4), range(7, 12), reversed(range(11) ) ) )

[(0, 7, 10), (1, 8, 9), (2, 9, 8), (3, 10, 7)]

##### 1.4. Lệnh thực thi một tập tin python

In [43]:
execfile('test.py')


hello


### Bài tập trên lớp

1. \
Lệnh mat1 = $np.zeros([5,5])$ sẽ tạo một ma trận 0 với kích thước $5*5$ \
Cụ thể , mat1 = $\left[\begin{matrix} 0 & 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 & 0 \end{matrix} \right] $

In [3]:
import numpy as np 
mat1 = np.zeros([5,5])
mat1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

2. \
Lệnh mat2 = $np.ones([5,5])$ sẽ tạo ra một ma trận có kích thước $5*5$ và có các phần tử bằng $1$  \
Cụ thể , mat2 = $\left[\begin{matrix} 1 & 1 & 1 & 1 & 1 \\ 1 & 1 & 1 & 1 & 1 \\ 1 & 1 & 1 & 1 & 1 \\ 1 & 1 & 1 & 1 & 1 \\ 1 & 1 & 1 & 1 & 1 \end{matrix} \right] $

In [4]:
mat2 = np.ones([5,5])
mat2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

3. \
Lệnh mat3 = mat1 + 2 * mat2 sẽ tạo ra một ma trận $mat3$ với các phần tử bằng với các phần tử tương ứng của $mat1$ + 2 * các phần tử tương của $mat2$, cụ thể như sau : \
mat3 = $\left[\begin{matrix} 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 \\ 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 \\ 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 \\ 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 \\ 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 & 0 + 2 * 1 \end{matrix} \right] = \left[\begin{matrix} 2 & 2 & 2 & 2 & 2 \\ 2 & 2 & 2 & 2 & 2 \\ 2 & 2 & 2 & 2 & 2 \\ 2 & 2 & 2 & 2 & 2 \\ 2 & 2 & 2 & 2 & 2 \end{matrix} \right]  $


In [5]:
mat3 = mat1 + 2*mat2
print(mat3)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


4. \
Lệnh mat4 = mat3 sẽ tạo ra một ma trận có các phần tử bằng với mat3. Khi một phần tử thay đổi trên mat3 thì phần tử tại vị trí tương ứng trong mat4 sẽ thay đổi theo bởi vì mat4 đang lưu địa chỉ của mat3 nên khi mat3 thay đổi thì mat4 sẽ thay đổi

In [10]:
mat4 = mat3
mat3[3][2] = 10
print("mat3", '\n' ,mat3)
print('mat4\n',mat4)

mat3 
 [[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]
mat4
 [[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]


5. \
Lệnh $mat5 = np.copy(mat3)$ sẽ tạo ra một ma trận $mat5$ là bản sao của $mat3$. Khi thay đổi trên $mat3$ sẽ không ảnh hưởng đến $mat5$

In [11]:
mat5 = np.copy(mat3)
mat3[3][2] = 8
print("mat3\n" , mat3)
print("mat4\n", mat4)
print("mat5\n", mat5)

mat3
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 8. 2. 2.]
 [2. 2. 2. 2. 2.]]
mat4
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 8. 2. 2.]
 [2. 2. 2. 2. 2.]]
mat5
 [[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]


6. \
Lệnh $mat6 = np.empty([4,5])$ sẽ tạo ra một ma trận $mat6$ với kích thước là 4*5 và các phần tử trong ma trận là ngẫu nhiên hoặc các giá trị từ bộ nhớ hiện tại

In [16]:
mat6 = np.empty([4,5])
mat6

array([[4.67296746e-307, 1.69121096e-306, 3.22647253e-307,
        1.89146896e-307, 7.56571288e-307],
       [4.00544531e-307, 1.11261095e-306, 3.56043054e-307,
        1.37961641e-306, 2.22518251e-306],
       [1.33511969e-306, 6.23037657e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307],
       [1.42418987e-306, 1.60219035e-306, 6.23057349e-307,
        9.34603679e-307, 1.24610994e-306]])

7. \
Lệnh $mat7 = np.identity(4)$ sẽ tạo một ma trận đơn vị $4*4$ \
Cụ thể , mat7 = $\left[\begin{matrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{matrix} \right] $

In [17]:
mat7 = np.identity(4)
mat7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

8. \
Lệnh $mat8 = np.random.random([4,5])$ sẽ tạo ra một ma trận kích thước $4*5$ và các phần tử trong ma trận là ngẫu nhiên

In [20]:
mat8 = np.random.random([4,5])
mat8

array([[0.34913055, 0.81267323, 0.40960416, 0.02380861, 0.48394641],
       [0.51018148, 0.04818897, 0.36257707, 0.1835322 , 0.15704607],
       [0.81512683, 0.64772485, 0.40753281, 0.93306247, 0.62403019],
       [0.92257116, 0.59205141, 0.77585951, 0.04760846, 0.99567277]])

### Bài tập chương 1

Bài 1

In [59]:
matrix = np.array([[7,8,9,5],[8,7,4,6],[7,5,8,6],[6,8,5,4],[9,9,8,7],[10,8,9,8]])
matrix.shape
percent = [0.1, 0.2, 0.3, 0.4]
AVG = np.dot(matrix,percent)
# print(AVG)
resume = []
passed = []
for i in range (len(AVG)):
    resume.append([chr(ord('A')+i),round(AVG[i],2)])
    if AVG[i] >= 5 :
        passed.append(chr(ord('A')+i))
print("Diem trung binh cua tung hoc sinh")
for student in resume :
    print(student)
print("Danh sach sinh vien qua mon ")
for student in passed :
    print(student) 

Diem trung binh cua tung hoc sinh
['A', 7.0]
['B', 5.8]
['C', 6.5]
['D', 5.3]
['E', 7.9]
['F', 8.5]
Danh sach sinh vien qua mon 
A
B
C
D
E
F


Bài 2 

In [63]:
# Sinh ngẫu nhiên ma trận 3*3 và có các phần tử nguyên từ 0 đến 10
matrix_random1 = np.random.randint(0,10,size=(3,3))
matrix_random2 = np.random.randint(0,10,size=(3,3))
print("Matrix 1 : \n",matrix_random1)
print("Matrix 2 : \n", matrix_random2)

Matrix 1 : 
 [[7 4 4]
 [2 0 0]
 [3 3 9]]
Matrix 2 : 
 [[2 3 7]
 [9 5 3]
 [9 4 4]]


In [66]:
# Tính tổng phần tử của mỗi ma trận 
sum_mat1 = sum(sum(matrix_random1))
sum_mat2 = sum(sum(matrix_random2))
print("Tong phan tu cua ma tran 1 : ", sum_mat1)
print("Tong phan tu cua ma tran 2 : ", sum_mat2)

Tong phan tu cua ma tran 1 :  32
Tong phan tu cua ma tran 2 :  46


In [72]:
mat1_row1 = np.linalg.norm(matrix_random1[0])
mat1_row3 = np.linalg.norm(matrix_random1[2])
mat2_row1 = np.linalg.norm(matrix_random2[0])
mat2_row3 = np.linalg.norm(matrix_random2[2])
print("Mat1_row1 : ",mat1_row1)
print("Mat1_row3 : ",mat1_row3)
print("Mat2_row1 : ",mat2_row1)
print("Mat2_row3 : ",mat2_row3)

# So sanh
if mat1_row1 > mat2_row1 :
    print("Mat1_row1 > Mat2_row1 ")
elif mat1_row1 < mat2_row1 :
    print("Math1_row1 < Mat2_row1")
else:
    print("Math1_row1 = Mat2_row1")

if mat1_row3 > mat2_row3 :
    print("Mat1_row3 > Mat2_row3")
elif mat1_row3 < mat2_row3 :
    print("Math1_row3 < Mat2_row3")
else:
    print("Math1_row3 = Mat2_row3")

Mat1_row1 :  9.0
Mat1_row3 :  9.9498743710662
Mat2_row1 :  7.874007874011811
Mat2_row3 :  10.63014581273465
Mat1_row1 > Mat2_row1 
Math1_row3 < Mat2_row3


In [75]:
# Tổng của hai ma trận 
C = matrix_random1 + matrix_random2
# Hiệu của hai ma trận
D = matrix_random1 - matrix_random2
# Tích hai ma trận
E = np.dot(matrix_random1,matrix_random2)
print("C\n", C)
print("D\n",D)
print("E\n",E)

C
 [[ 9  7 11]
 [11  5  3]
 [12  7 13]]
D
 [[ 5  1 -3]
 [-7 -5 -3]
 [-6 -1  5]]
E
 [[ 86  57  77]
 [  4   6  14]
 [114  60  66]]


Bài 3

In [77]:
# Sinh vector
vector1 = np.linspace(0,100,21)
print(vector1)

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]


- a) Dùng lệnh split, chia nhỏ vector kia ra thành 3 vector con, đặt là u, v, w

In [81]:
u,v,w = np.split(vector1,3)
print("u\n", u)
print("v\n",v)
print("w\n",w)

u
 [ 0.  5. 10. 15. 20. 25. 30.]
v
 [35. 40. 45. 50. 55. 60. 65.]
w
 [ 70.  75.  80.  85.  90.  95. 100.]


- b) Tính $u*v$ và $v.dot(w)$

In [84]:
mat_res = u*v
mat_res1 = v.dot(w)
print("u*v\n",mat_res)
print("v.dot(w)\n",mat_res1) 

u*v
 [   0.  200.  450.  750. 1100. 1500. 1950.]
v.dot(w)
 30450.0


- c)