### Bài tập chương 2

Câu 1

- Vấn đề 1: Tìm giao điểm giữa hai đường thẳng trong $\mathbb{R}^2$

In [19]:
import numpy as np 
A = np.array([[1,-1], [2,3]])
B = np.array([-2,6])
ans = np.linalg.solve(A,B)
print(ans)

[0. 2.]


- Vấn đề 2 : Tìm giao điểm giữa 3 mặt phẳng trong $\mathbb{R}^3$

In [14]:
A = np.array([[1,-1,0], [2, -1, -1], [1,1,1]])
B = np.array([2,3,6])
ans = np.linalg.solve(A,B)
print(ans)

[3. 1. 2.]


- Vấn đề 3 : Tìm các hệ số đa thức để đa thức thỏa mãn các nghiệm :
$P(x) = ax^2 + bx + c, P(1) = 4, P(2) = 3 , P(3) = 4$ 

Giải : \
Ta có : 
+ $P(1) = a + b + c = 4 (1)$ 
+ $P(2) = 4a + 2b + c = 3 (2)$ 
+ $P(3) = 9a + 3b + c = 4 (3)$ \
$Từ (1), (2), (3) => a = 1 , b = -4 , c = 7 $

In [24]:
A = np.array([[1,1,1], [4,2,1], [9,3,1]])
B = np.array([4,3,4])
ans = np.linalg.solve(A,B)
print(ans)

[ 1. -4.  7.]


- Vấn đề 4 : Tìm hệ các đa thức khi phân rã để tính tích phân

In [35]:
A = np.array([[1,0,1], [1,1,-2], [-2,2,1]])
B = np.array([1,-3,0])
ans = np.linalg.solve(A,B)
print(ans)

x = np.arange(0,1.1,0.01)

y = ans[0]/(x-1) + ans[1]/((x-1)**2) + ans[2]/(x+2)

np.trapz(y)

[-0.11111111 -0.66666667  1.11111111]


C:\Users\ADMIN\AppData\Local\Temp\ipykernel_11896\3221327472.py:8: RuntimeWarning: divide by zero encountered in divide
  y = ans[0]/(x-1) + ans[1]/((x-1)**2) + ans[2]/(x+2)


-inf

Câu 2

In [20]:
# Vấn đề 1 
import sympy as sp
X = sp.Symbol('x')
Y = sp.Symbol('y')
sp.solve([X - Y + 2,2*X + 3*Y -6], [X,Y])

{x: 0, y: 2}

In [22]:
# Vấn đề 2
X = sp.Symbol('x')
Y = sp.Symbol('y')
Z = sp.Symbol('z')
sp.solve([X - Y - 2, 2*X - Y - Z - 3, X + Y + Z - 6], [X,Y,Z])


{x: 3, y: 1, z: 2}

In [23]:
# Vấn đề 3
a = sp.Symbol('a')
b = sp.Symbol('b')
c = sp.Symbol('c')
sp.solve([a+b+c-4, 4*a + 2*b +c - 3, 9*a + 3*b + c - 4], [a,b,c])

{a: 1, b: -4, c: 7}

In [25]:
# Vấn đề 4 
a = sp.Symbol('a')
b = sp.Symbol('b')
c = sp.Symbol('c')
sp.solve([a+c-1, a + b - 2*c +3, -2*a + 2*b +c], [a,b,c])

{a: -1/9, b: -2/3, c: 10/9}

Câu 3

In [29]:
F = np.array([[1,1],[1,0]])

k = int(input())

for i in range(k-1) :
    F = F.dot(F)
print(F)

[[2 1]
 [1 1]]


- Chứng minh $F_k$ chứa 3 phần tử của $Fibo_{k+1}, Fibo_k, Fibo_{k-1}$ 
Ta có : 
+ $F = \left[\begin{matrix} 1&1 \\ 1&0 \end{matrix}\right]$ 
+ Với k = 1, Ta có : Fibo[0] = 0 = F[1][1], Fibo[1] = 1 = F[0][1], Fibo[2] = 1 = F[0][0] \
\
Như vậy , ta có thể biểu diễn F dưới dạng : $\left[\begin{matrix} Fibo_2&Fibo_1 \\ Fibo_1&Fibo_0 \end{matrix}\right]$ \
Ta chứng minh với k + 1 : \
\
$F_{k+1} = F_k * F = \left[\begin{matrix} Fibo_{k+1}& Fibo_k \\ Fibo_k && Fibo_{k-1} \end{matrix}\right] * \left[\begin{matrix} 1&1 \\ 1&0 \end{matrix}\right] = \left[\begin{matrix} Fibo_{k+1} + Fibo_k && Fibo_{k+1} \\ Fibo_{k+1} && Fibo_k\end{matrix}\right] = \left[\begin{matrix} Fibo_{k+2} & Fibo_{k+1} \\ Fibo_{k+1} && Fibo_k \end{matrix}\right] = \left[\begin{matrix} Fibo_{(k+1)+1} & Fibo_{k+1} \\ Fibo_{k+1} && Fibo_{(k+1)-1} \end{matrix}\right] $\
\
Vậy $F_k$ chứa 3 phần tử của $Fibo_{k+1}, Fibo_k, Fibo_{k-1}$ 