#### Câu 1 : Viết bài thu hoạch (làm từng bước như bài toán ứng dụng 1) về nội dung :

##### a) Tự chọn một ma trận nghịch đảo 3x3 . Sinh viên chứng minh ma trận đó khả nghịch ( tồn tại ma trận nghịch đảo )

In [12]:
import numpy as np
A  = np.array([[1, 2, 3], [4, 9, 1], [7, 1, 6]])

# ma trận A khả nghịch vì det(A)!=0

print(np.linalg.det(A))

# nên A tồn tại ma trận nghịch đảo

A_inv = np.linalg.inv(A)
A_inv

-158.00000000000003


array([[-0.33544304,  0.05696203,  0.15822785],
       [ 0.10759494,  0.09493671, -0.06962025],
       [ 0.37341772, -0.08227848, -0.00632911]])

##### b) Nhập họ và tên của sinh viên

In [13]:
full_name = input('Input Name: ')

In [14]:
def endcoding(full_name):
  i = 0
  result = []
  # quy ước rỗng ta ký hiệu $
  while i <len(full_name):
    res = []
    cur = []
    for j in range(3):
        c = '$'
        if i+j<len(full_name):
            c = full_name[i+j]
        cur.append(c)
        res.append(ord(c))
    res = np.array(res)
    i += 3
    # print(cur, end = ':')
    # print(res.dot(A))
    print(A.shape, end = ":")
    print(res)
    result.append(res.dot(A))
  return np.matrix(result)

endcoding(full_name)

(3, 3):[ 84 114 105]
(3, 3):[110 104  32]
(3, 3):[ 68 117 111]
(3, 3):[110 103  32]
(3, 3):[ 72 111  97]
(3, 3):[110  36  36]


matrix([[1275, 1299,  996],
        [ 750, 1188,  626],
        [1313, 1300,  987],
        [ 746, 1179,  625],
        [1195, 1240,  909],
        [ 506,  580,  582]])

In [15]:
def encode(full_name):
    i = 0
    encoded_data = []

    while i < len(full_name):
        res = []
        for j in range(3):
            c = "$"
            if i + j < len(full_name):
                c = full_name[i + j]
            res.append(ord(c))
        res = np.array(res)
        i += 3
        encoded_data.append(res.dot(A))
    return np.matrix(encoded_data)

encode(full_name)

matrix([[1275, 1299,  996],
        [ 750, 1188,  626],
        [1313, 1300,  987],
        [ 746, 1179,  625],
        [1195, 1240,  909],
        [ 506,  580,  582]])

In [16]:
def  decode(encode_data):
    for i in encode_data:
        cur = np.array(i.dot(A_inv))
        print(cur)

decode(encode(full_name))

[[ 84. 114. 105.]]
[[110. 104.  32.]]
[[ 68. 117. 111.]]
[[110. 103.  32.]]
[[ 72. 111.  97.]]
[[110.  36.  36.]]


#### Câu 2

- a)

In [17]:
from fractions import Fraction as F
def solve(c : list) :
    A = np.array([[1,0],[0,1]])
    for x in c :
        temp = np.array([[x,1],[1,0]])
        A = A.dot(temp)

    return A[0][0], A[1][0]

lst  =  [1,2,3]
p,n = solve(lst)
Ans =F(p,n)
print(Ans)

10/7


##### b)

Với n = 1 , ta có : \
$\begin{bmatrix} c_0&1 \\ 1&0 \end{bmatrix} = \begin{bmatrix} p_0&p_{-1} \\ q_0 & q_{-1} \end{bmatrix}$ \
Với $p_0 = c_0, p_{-1}= 1, q_0 = 1, q_{-1}= 0.$ Điều này khớp với công thức đã cho \
Giả sử công thức đúng với n = k , ta chứng minh với n = k+1 \
Ta có : \
$\begin{bmatrix} c_{k+1}&1 \\ 1&0 \end{bmatrix} * \begin{bmatrix} p_{k}&p_{k-1} \\ q_{k} & q_{k-1} \end{bmatrix} = \begin{bmatrix} c_{k+1}p_k + p_{k-1} & c_{k+1}p_{k-1}+p_{k-2} \\ c_{k+1}q_k + q_{k-1} & c_{k+1}q_{k-1}+q_{k-2} \end{bmatrix}$ \
So sánh với công thức đã cho , ta thấy nó khớp nếu $p_{k+1} = c_{k+1}p_k + p_{k-1} và q_{k+1} = c_{k+1}q_k + q_{k-1} $. Điều này chứng minh công thức đúng với mọi n