### $$\text{Bài tập chương 8}$$

**Bài 1**

- Kiểm tra điều kiện f1

In [30]:
import sympy as sp 
import numpy as np
from sympy import lambdify


In [17]:
v1,v2= sp.symbols('v1 v2')

In [18]:
bieuthuc1 = v1 - v2

In [19]:
f1 = lambdify([v1,v2], bieuthuc1, 'numpy')

In [20]:
a, b = sp.symbols('a b')      
c, d = sp.symbols('c d')  
e = sp.symbols('e')

In [24]:
check1 = (e*f1(a,b) + f1(c,d)).equals( f1(e*a+c, e*b+d))

True

- Kiểm tra điều kiện f2

In [25]:
bieuthuc2 = v1 + 2 *v2

v1 + 2*v2

In [26]:
f2 = lambdify([v1,v2], bieuthuc1, 'numpy')

<function _lambdifygenerated(v1, v2)>

In [27]:
a, b = sp.symbols('a b')      
c, d = sp.symbols('c d')  
e = sp.symbols('e')

In [28]:
check2 = (e*f1(a,b) + f1(c,d)).equals( f1(e*a+c, e*b+d))

True

In [29]:
if check1 and check2 :
    print("Ánh xạ trên là ánh xạ tuyến tính")
else :
    print("Ánh xạ trên không phải ánh xạ tuyến tính")
    

Ánh xạ trên là ánh xạ tuyến tính


**Bài 2**

In [31]:
A = np.array([[13, -5], [-5, 13]])
A

array([[13, -5],
       [-5, 13]])

In [32]:
D, P = np.linalg.eig(A)
D, P

(array([18.,  8.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

In [33]:
conic = np.arccos(P[0][0])
print(np.degrees(conic))

45.0


In [34]:
x_prime, y_prime = sp.symbols('x_prime y_prime')

lambda_1 = 8
lambda_2 = 18
f = -72

equation = lambda_1 * x_prime**2 + lambda_2 * y_prime**2 - f

print("Phương trình:", equation)

Phương trình: 8*x_prime**2 + 18*y_prime**2 + 72
