### $$\text{BÀI TẬP CHƯƠNG 7}$$

**Bài 1**

In [1]:
import numpy as np


In [11]:
def g(x,y,z) :
    return np.array([x+y,z+2,0])

In [15]:
X = np.random.randint(0,10,3)
Y = np.random.randint(0,10,3)

X,Y, X+Y

(array([3, 9, 2]), array([4, 0, 8]), array([ 7,  9, 10]))

In [16]:
g(*X)

array([12,  4,  0])

In [17]:
g(*Y)

array([ 4, 10,  0])

In [18]:
g(*(X+Y))

array([16, 12,  0])

$\text{Ta thấy rằng g(X+Y)} \ne \text{g(X) + g(Y) nên g(x,y,z) = (x+y,z+2,0) không phải một ánh xạ tuyến tính}$

**Bài 2**

In [20]:
# Tập các điểm tạo thành chữ F 
P = np.array([[0,0,3,3,1,1,2,2,1,1], [0,5,5,4,4,3,3,2,2,0]])
P

array([[0, 0, 3, 3, 1, 1, 2, 2, 1, 1],
       [0, 5, 5, 4, 4, 3, 3, 2, 2, 0]])

In [24]:
maxtrix_change = np.array([[0,1],[1,-1]])
vec_delta = np.array([4,2])
P_ans = (P.T @ maxtrix_change + vec_delta).T
P_ans

array([[ 4,  9,  9,  8,  8,  7,  7,  6,  6,  4],
       [ 2, -3,  0,  1, -1,  0,  1,  2,  1,  3]])