#### Bài 1

- a

In [18]:
import numpy as np 


A = np.array([[1,4,8],[2,0,1],[2,0,4]])

C = np.eye(3)
for i in range (3) :
    for j in range(3) :
        temp = np.delete(np.delete(A,i,axis=0),j,axis=1)
        C[i][j] = np.linalg.det(temp)
print(C)

[[  0.   6.   0.]
 [ 16. -12.  -8.]
 [  4. -15.  -8.]]


- b

In [19]:
Adj = C.T
Adj

array([[  0.,  16.,   4.],
       [  6., -12., -15.],
       [  0.,  -8.,  -8.]])

### Bài 2

In [30]:
import numpy as np
from sympy import *

def matrix_circle(x1,y1,x2,y2,x3,y3) :
    x,y = symbols('x y')
    M = Matrix([[x*x + y*y, x,y,1],[x1**2 + y1**2, x1,y1,1],[x2**2 + y2**2, x2,y2,1],[x3**2 + y3**2, x3,y3,1]])
    return M.det()
print('Phuong trinh duong tron : ',matrix_circle(2,1,1,4,4,8))

Phuong trinh duong tron :  -13*x**2 + 141*x - 13*y**2 + 99*y - 316
